apiVersion: apps/v1
kind: Deployment
metadata:
  name: items-mongo-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: items-mongo
  template:
    metadata:
      labels:
        app: items-mongo
    spec:
      containers:
        - name: items-mongo
          image: mongo
---
apiVersion: v1
kind: Service
metadata:
  name: items-mongo-srv
spec:
  type: ClusterIP ## get DB port forwarding just for testing (should be removed)
  selector:
    app: items-mongo
  ports:
    - name: items-mongo-db # only for internal logging purposes
      protocol: TCP
      port: 27017
      targetPort: 27017
